trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '24.x'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '$(nodeVersion)'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: |
      sed -i "s|#CONTENTFUL_SPACE_ID#|$(CONTENTFUL_SPACE_ID)|g" src/environments/environment.ts
      sed -i "s|#CONTENTFUL_DELIVERY_TOKEN#|$(CONTENTFUL_DELIVERY_TOKEN)|g" src/environments/environment.ts
    displayName: 'Replace Contentful environment variables'

  - script: npm run build
    displayName: 'Build Angular application'

  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Azure Static Web Apps'
    inputs:
      app_location: 'dist/portfolio/browser'
      skip_app_build: true
      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'